trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.Repository.LocalPath)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Archive files'

- upload: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  artifact: 'drop'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'connection'
    appType: 'webApp'
    WebAppName: 'mdpfportal'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  displayName: 'Azure App Service Deploy'